export const ASSETS = {
  castle: "/assets/castle-original.jpg",
  login: "/assets/coastal-castle.jpg",
  quests: "/assets/references/quests-page.png",
  training: "/assets/references/training.png",
  dormitory: "/assets/references/dormitory.png",
  armory: "/assets/references/armory.png",
  forge: "/assets/references/forge.png",
  infirmary: "/assets/references/infirmary.png",
  alchemy: "/assets/references/alchemy.png",
  treasury: "/assets/references/treasury.png",
  market: "/assets/references/market-square.png",
  parchment: "/assets/references/parchment-map.png",
  mage: "/assets/references/mage-tower.png",
};
// Coordonnées relatives au décor, hors barre de navigation (756 × 581).
// L'ordre de ce tableau pilote celui de la barre latérale (.room-nav) ; il
// n'a aucune incidence sur la position des tuiles du château, placées via
// leurs propres x/y (position absolue). Ordre demandé par Bruno (2026-09-22) :
// arsenal / dortoirs / infirmerie / entraînement / forge / armurerie / tour
// du mage / laboratoire / trésorerie / marché / quêtes.
export const LOCATIONS = [
  {
    id: "stock",
    name: "Arsenal",
    x: 38,
    y: 66.5,
    w: 15.6,
    h: 21,
    icon: [45, 389, 61, 49],
    description: "L’inventaire de la forteresse.",
  },
  {
    id: "dortoirs",
    name: "Dortoirs",
    x: 52.7,
    y: 47.6,
    w: 15.6,
    h: 21,
    icon: [49, 83, 55, 48],
    description: "Les compagnons de la forteresse.",
  },
  {
    id: "infirmerie",
    name: "Infirmerie",
    x: 73.2,
    y: 47.6,
    w: 15.6,
    h: 21,
    icon: [373, 232, 51, 48],
    description: "Repos et soins des compagnons.",
  },
  {
    id: "entrainement",
    name: "Terrain d’Entraînement",
    x: 87.6,
    y: 85.6,
    w: 15.6,
    h: 21,
    icon: [637, 487, 47, 52],
    description: "L’instructeur et ses élèves.",
  },
  {
    id: "forge",
    name: "Forge",
    x: 64.7,
    y: 66.5,
    w: 15.6,
    h: 21,
    icon: [328, 426, 54, 47],
    description: "Des ressources aux armes.",
  },
  {
    id: "armurerie",
    name: "Armurerie",
    x: 51.35,
    y: 66.5,
    w: 15.6,
    h: 21,
    icon: [205, 399, 56, 61],
    description: "Armures, protections et équipements.",
  },
  {
    id: "mage",
    name: "Tour du Mage",
    x: 39.2,
    y: 16.5,
    w: 15.6,
    h: 21,
    icon: [244, 99, 42, 51],
    description: "Formules et arcanes du mage de la compagnie.",
  },
  {
    id: "alchimie",
    name: "Laboratoire Alchimiste",
    x: 89.3,
    y: 51.8,
    w: 15.6,
    h: 21,
    icon: [542, 346, 51, 55],
    description: "Potions et composants mystérieux.",
  },
  {
    id: "tresorerie",
    name: "Trésorerie",
    x: 39,
    y: 32,
    w: 15.6,
    h: 21,
    icon: [211, 260, 50, 50],
    description: "Le registre des pièces d’or.",
  },
  {
    id: "marche",
    name: "Marché",
    x: 10.2,
    y: 86.8,
    w: 15.6,
    h: 21,
    icon: [43, 509, 59, 54],
    description: "Achetez de quoi préparer l’aventure.",
  },
  {
    id: "quetes",
    name: "Quêtes",
    x: 86,
    y: 11.5,
    w: 23,
    h: 23,
    description: "Les prochaines aventures de la compagnie.",
  },
];
export const CLASSES = [
  "Légende",
  "Guerrier",
  "Roublard",
  "Rôdeur",
  "Prêtre",
  "Druide",
  "Incantateur",
  "Paladin",
];
export const ITEMS = [
  {
    id: "maille",
    name: "Cotte de mailles",
    type: "Armures",
    price: 180,
    description: "Une maille robuste pour les longues expéditions.",
    source: "armory",
    crop: [17, 73, 159, 152],
    metal: 30,
    leather: 8,
    wood: 30,
    defense: "+3",
  },
  {
    id: "epee",
    name: "Épée longue",
    type: "Armes",
    price: 50,
    description: "Une lame équilibrée, forgée pour durer.",
    source: "forge",
    crop: [23, 76, 179, 185],
    metal: 10,
    leather: 5,
    wood: 2,
    defense: "+5",
  },
  {
    id: "potion",
    name: "Potion de soin",
    type: "Potions",
    price: 25,
    description: "Restaure un point de vie à votre personnage.",
    icon: "alchimie",
  },
  { id: "potion-energy", name: "Potion d’énergie", type: "Potions", craftOnly: true, description: "Préparation vivifiante. Effets à définir avec Bruno et à appliquer manuellement.", icon: "alchimie" },
  { id: "potion-clarity", name: "Potion de clairvoyance", type: "Potions", craftOnly: true, description: "Préparation des sens. Effets à définir avec Bruno et à appliquer manuellement.", icon: "alchimie" },
  { id: "formule-bouclier", name: "Formule de Bouclier", type: "Formules", craftOnly: true, description: "Invocation de démonstration. Effets à définir avec Bruno et à appliquer manuellement.", icon: "mage" },
  { id: "formule-foudroiement", name: "Formule de Foudroiement", type: "Formules", craftOnly: true, description: "Invocation de démonstration. Effets à définir avec Bruno et à appliquer manuellement.", icon: "mage" },
  { id: "formule-vision", name: "Formule de Vision", type: "Formules", craftOnly: true, description: "Invocation de démonstration. Effets à définir avec Bruno et à appliquer manuellement.", icon: "mage" },
];
export const INITIAL = {
  gold: 905,
  // Métal/Cuir/Bois : lignes ordinaires de l'inventaire (comme n'importe
  // quel autre objet), pas un compteur séparé. Ces valeurs ne servent que
  // de démonstration locale ; dès qu'un objet Fer/Métal/Cuir/Bois existe
  // dans le catalogue admin, la fusion au démarrage (App.jsx) remplace ces
  // lignes par la quantité réelle saisie par l'admin — un seul compteur par
  // matériau, qu'il vienne de la démo ou de l'Arsenal admin.
  inventory: [
    { id: "material:metal", quantity: 45, equipped: false, nom: "Métal", categorie: "Matériaux" },
    { id: "material:leather", quantity: 18, equipped: false, nom: "Cuir", categorie: "Matériaux" },
    { id: "material:wood", quantity: 40, equipped: false, nom: "Bois", categorie: "Matériaux" },
  ],
  stock: { maille: 3, epee: 5, potion: 8 },
  log: [],
  health: 2,
  quest: false,
};
